import requests

# Use the access token you obtained earlier
access_token = "your_access_token_here"

# Catalog conformance declaration API endpoint
url = "https://data.dataspace.copernicus.eu/catalog/conformance"

# Set the authorization headers with the access token
headers = {
    'Authorization': f'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJYVUh3VWZKaHVDVWo0X3k4ZF8xM0hxWXBYMFdwdDd2anhob2FPLUxzREZFIn0.eyJleHAiOjE3MjYzMDc0MzMsImlhdCI6MTcyNjMwNjgzMywianRpIjoiYWU0YWRmN2ItNzFjZC00ZWNmLWFmM2ItY2U1YzI1NjUzYWM4IiwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS5kYXRhc3BhY2UuY29wZXJuaWN1cy5ldS9hdXRoL3JlYWxtcy9DRFNFIiwic3ViIjoiZTFkMGEwZmItZWMyYS00OTliLTgyYmUtMmVmMWYyN2EwMmMyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic2gtMzAyY2M1ZmYtOWQ5MC00NGM3LTk0ZWYtODAxMzM5MDJhYzI1Iiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIHVzZXItY29udGV4dCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiY2xpZW50SG9zdCI6IjgzLjI0OC43MC4xMzQiLCJvcmdhbml6YXRpb25zIjpbImRlZmF1bHQtMGFjMzNiYWMtZDI2Yy00NTRmLWFjOGUtYWExOGVkYTNlMTNkIl0sInVzZXJfY29udGV4dF9pZCI6ImRlMDdhMTBkLTViNmItNGNkMy04ZjFhLTkxNWFlZWJkMzQxNSIsImNvbnRleHRfcm9sZXMiOnt9LCJjb250ZXh0X2dyb3VwcyI6WyIvYWNjZXNzX2dyb3Vwcy91c2VyX3R5cG9sb2d5L2NvcGVybmljdXNfZ2VuZXJhbC8iLCIvb3JnYW5pemF0aW9ucy9kZWZhdWx0LTBhYzMzYmFjLWQyNmMtNDU0Zi1hYzhlLWFhMThlZGEzZTEzZC8iXSwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LXNoLTMwMmNjNWZmLTlkOTAtNDRjNy05NGVmLTgwMTMzOTAyYWMyNSIsInVzZXJfY29udGV4dCI6ImRlZmF1bHQtMGFjMzNiYWMtZDI2Yy00NTRmLWFjOGUtYWExOGVkYTNlMTNkIiwiY2xpZW50QWRkcmVzcyI6IjgzLjI0OC43MC4xMzQiLCJjbGllbnRfaWQiOiJzaC0zMDJjYzVmZi05ZDkwLTQ0YzctOTRlZi04MDEzMzkwMmFjMjUifQ.k-2KEGl1rgO0OKC92wmhhzJFQA8YPxkJfoQBoNOio41BerHehrg4tBmyRlVS4u4HY1k6xZ4hVkIM9SvZjy2WbbI1ccVsWXjY5Z8GW_FK0LpRTGjEkuRh2yEgBvwn-WlDYYSbwfNIefq-B5SZSxkONzdmSBmDMSLfXzzZ11TP7sBEUEGtvWn9J3VW-GDZzoXzmh43rhbDzOmgFnVTat7Nnwk09xRsQ1TbEJr81l5tC71ejlm3GIpDgQHNztJPa9gMX9O29bWhuljyb9IvbhQSLCU9sSZ1DgReuFcNqOtmVu95BQg4SBNNTybEQsN4CdeCqi5u1wD7O81OwqSk9y9rdA'
}

# Send the GET request to access the conformance declaration
response = requests.get(url, headers=headers)

# Check if the request was successful
if response.status_code == 200:
    # Print the conformance declaration data
    print("Conformance Declaration:", response.json())
else:
    # Print the error message if something went wrong
    print(f"Error: {response.status_code}, {response.text}")
